### ISSUE TITLE
ArcMap 10.5.1

### ISSUE THREAD

**Issue by ManuelWidauer** [msgis/swwat-gzp-template#1]
Sehr geehrte Frau Sattler!

Da wir im Amt der Salzburger Landesregierung aktuell noch die Version 10.5.1 von ArcMap verwenden, wäre es hier vielleicht möglich den GTO und die Datentemplates in dieser Version für uns zur Verfügung zu stellen?
Eine Aktualisierung von ArcMap wird bei uns nur in gewissen Jahresabständen durchgeführt.

Mit freundlichen Grüßen

Manuel Widauer
Wasser Informationssystem Salzburg

Land Salzburg
Abteilung: Wasser
Referat: Allgemeine Wasserwirtschaft
Michael-Pacher-Straße 36, 5020 Salzburg
Tel.: +43 662 8042-4316
mailto: wasser@salzburg.gv.at
http://www.salzburg.gv.at

**Comment by katrinsattler** [comment]
GTO Installation und mxd für ArcMap 10.5 per Email versandt.
