### ISSUE TITLE
template in epsg 31255?

### ISSUE THREAD

**Issue by zoran2k** [msgis/swwat-gzp-template#2]
Hi Nilüfer,

Do you also provide a template in epsg 31255?
We are a cunsulting engineer in Upper Austria and deliver almost all GZP projects in GK central,

Thank you, all the best,
Andreas

**Comment by nilufercipa** [comment]
Hi Andreas, 

You can find the template in EPSG 31255 in the [releases section ](https://github.com/msgis/swwat-gzp-template/releases) now. I hope it helps. 

All the best, 
Nilüfer
